version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  java-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_management
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data:
