spring:
  application:
    name: schoolmanagement
  datasource:
    url: jdbc:postgresql://localhost:5437/demo?schema=public
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
